version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis-token-store
    ports:
      - "6379:6379"
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
